### ISSUE TITLE
compilation fails with gfortran

### ISSUE THREAD

**Issue by svaverbe** [pmaxted/ellc#5]
I have tried to install ellc in python anaconda, but the build fails with the following errors:

  compiling Fortran 90 module sources
  creating build/temp.linux-x86_64-3.7/ellc
  Fortran f77 compiler: /home/siegfried/anaconda3/envs/CARMENES/bin/x86_64-conda_cos6-linux-gnu-gfortran -Wall -g -ffixed-form -fno-second-underscore -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -O3 -funroll-loops
  Fortran f90 compiler: /home/siegfried/anaconda3/envs/science/bin/x86_64-conda_cos6-linux-gnu-gfortran -Wall -g -fno-second-underscore -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -O3 -funroll-loops
  Fortran fix compiler: /home/siegfried/anaconda3/envs/science/bin/x86_64-conda_cos6-linux-gnu-gfortran -Wall -g -ffixed-form -fno-second-underscore -Wall -g -fno-second-underscore -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -O3 -funroll-loops
  creating build/temp.linux-x86_64-3.7/f_src
  compile options: '-Ibuild/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7 -I/home/siegfried/anaconda3/envs/CARMENES/lib/python3.7/site-packages/numpy/core/include -I/home/siegfried/anaconda3/envs/CARMENES/include/python3.7m -c'
  extra options: '-Jbuild/temp.linux-x86_64-3.7/ellc -Ibuild/temp.linux-x86_64-3.7/ellc'
  x86_64-conda_cos6-linux-gnu-gfortran:f90: ./f_src/constants.f90
  x86_64-conda_cos6-linux-gnu-gfortran:f90: ./f_src/utils.f90
  ./f_src/utils.f90:1071:47:

   double precision function unitfunc(u,v,npar,par,verbose)
                                                 1
  Warning: Unused dummy argument 'par' at (1) [-Wunused-dummy-argument]
  ./f_src/utils.f90:1071:36:

   double precision function unitfunc(u,v,npar,par,verbose)
                                      1
  Warning: Unused dummy argument 'u' at (1) [-Wunused-dummy-argument]
  ./f_src/utils.f90:1071:38:

   double precision function unitfunc(u,v,npar,par,verbose)
                                        1
  Warning: Unused dummy argument 'v' at (1) [-Wunused-dummy-argument]
  ./f_src/utils.f90:1071:55:

   double precision function unitfunc(u,v,npar,par,verbose)
                                                         1
  Warning: Unused dummy argument 'verbose' at (1) [-Wunused-dummy-argument]
  x86_64-conda_cos6-linux-gnu-gfortran:f90: ./f_src/coords.f90
  x86_64-conda_cos6-linux-gnu-gfortran:f90: ./f_src/gauss_legendre.f90
  x86_64-conda_cos6-linux-gnu-gfortran:f90: ./f_src/solve_real_poly.f90
  x86_64-conda_cos6-linux-gnu-gfortran:f90: ./f_src/ellipse.f90
  x86_64-conda_cos6-linux-gnu-gfortran:f90: ./f_src/stellar.f90
  ./f_src/stellar.f90:189:0:

       if(d.eq.bad_dble) return

  Warning: 'd' may be used uninitialized in this function [-Wmaybe-uninitialized]
  ./f_src/stellar.f90:189:0: Warning: 'd' may be used uninitialized in this function [-Wmaybe-uninitialized]
  x86_64-conda_cos6-linux-gnu-gfortran:f90: ./f_src/spots.f90
  x86_64-conda_cos6-linux-gnu-gfortran:f90: ./f_src/ellc.f90
  ./f_src/ellc.f90:1815:0:

       flux_rv_flag(iobs,1) = (flux_1+flux_2+flux_3+refl_1+refl_2)/fnorm

  Warning: 'flux_3' may be used uninitialized in this function [-Wmaybe-uninitialized]
  ./f_src/ellc.f90:1558:0:

         ii = ii_2(iobs,i_spot)

  Warning: 'ii_2.dim[1].stride' may be used uninitialized in this function [-Wmaybe-uninitialized]
  ./f_src/ellc.f90:1558:0: Warning: 'ii_2.offset' may be used uninitialized in this function [-Wmaybe-uninitialized]
  ./f_src/ellc.f90:1371:0:

         ii = ii_1(iobs,i_spot)

  Warning: 'ii_1.dim[1].stride' may be used uninitialized in this function [-Wmaybe-uninitialized]
  ./f_src/ellc.f90:1371:0: Warning: 'ii_1.offset' may be used uninitialized in this function [-Wmaybe-uninitialized]
  ./f_src/ellc.f90:1559:0:

         df = df_2(iobs,i_spot)

  Warning: 'df_2.dim[1].stride' may be used uninitialized in this function [-Wmaybe-uninitialized]
  ./f_src/ellc.f90:1559:0: Warning: 'df_2.offset' may be used uninitialized in this function [-Wmaybe-uninitialized]
  ./f_src/ellc.f90:1372:0:

         df = df_1(iobs,i_spot)

  Warning: 'df_1.dim[1].stride' may be used uninitialized in this function [-Wmaybe-uninitialized]
  ./f_src/ellc.f90:1372:0: Warning: 'df_1.offset' may be used uninitialized in this function [-Wmaybe-uninitialized]
  compiling Fortran sources
  Fortran f77 compiler: /home/siegfried/anaconda3/envs/CARMENES/bin/x86_64-conda_cos6-linux-gnu-gfortran -Wall -g -ffixed-form -fno-second-underscore -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -O3 -funroll-loops
  Fortran f90 compiler: /home/siegfried/anaconda3/envs/science/bin/x86_64-conda_cos6-linux-gnu-gfortran -Wall -g -fno-second-underscore -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -O3 -funroll-loops
  Fortran fix compiler: /home/siegfried/anaconda3/envs/science/bin/x86_64-conda_cos6-linux-gnu-gfortran -Wall -g -ffixed-form -fno-second-underscore -Wall -g -fno-second-underscore -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -O3 -funroll-loops
  compile options: '-Ibuild/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7 -I/home/siegfried/anaconda3/envs/CARMENES/lib/python3.7/site-packages/numpy/core/include -I/home/siegfried/anaconda3/envs/CARMENES/include/python3.7m -c'
  extra options: '-Jbuild/temp.linux-x86_64-3.7/ellc -Ibuild/temp.linux-x86_64-3.7/ellc'
  x86_64-conda_cos6-linux-gnu-gfortran:f90: build/src.linux-x86_64-3.7/ellc_f-f2pywrappers2.f90
  /home/siegfried/anaconda3/envs/science/bin/x86_64-conda_cos6-linux-gnu-gfortran -Wall -g -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7/ellc_fmodule.o build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/fortranobject.o build/temp.linux-x86_64-3.7/f_src/constants.o build/temp.linux-x86_64-3.7/f_src/utils.o build/temp.linux-x86_64-3.7/f_src/coords.o build/temp.linux-x86_64-3.7/f_src/gauss_legendre.o build/temp.linux-x86_64-3.7/f_src/solve_real_poly.o build/temp.linux-x86_64-3.7/f_src/ellipse.o build/temp.linux-x86_64-3.7/f_src/stellar.o build/temp.linux-x86_64-3.7/f_src/spots.o build/temp.linux-x86_64-3.7/f_src/ellc.o build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7/ellc_f-f2pywrappers2.o -L/home/siegfried/anaconda3/envs/CARMENES/bin/../x86_64-conda_cos6-linux-gnu/sysroot/lib/../lib -L/home/siegfried/anaconda3/envs/CARMENES/bin/../x86_64-conda_cos6-linux-gnu/sysroot/lib/../lib -lgfortran -o build/lib.linux-x86_64-3.7/ellc/ellc_f.cpython-37m-x86_64-linux-gnu.so
  /home/siegfried/anaconda3/envs/science/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/siegfried/anaconda3/envs/science/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib/../lib/Scrt1.o: in function `_start':
  /home/rdonnelly/mc/conda-bld/compilers_linux-64_1534865402226/work/.build/src/glibc-2.12.2/csu/../sysdeps/x86_64/elf/start.S:99: undefined reference to `main'
  collect2: error: ld returned 1 exit status
  error: Command "/home/siegfried/anaconda3/envs/science/bin/x86_64-conda_cos6-linux-gnu-gfortran -Wall -g -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7/ellc_fmodule.o build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/fortranobject.o build/temp.linux-x86_64-3.7/f_src/constants.o build/temp.linux-x86_64-3.7/f_src/utils.o build/temp.linux-x86_64-3.7/f_src/coords.o build/temp.linux-x86_64-3.7/f_src/gauss_legendre.o build/temp.linux-x86_64-3.7/f_src/solve_real_poly.o build/temp.linux-x86_64-3.7/f_src/ellipse.o build/temp.linux-x86_64-3.7/f_src/stellar.o build/temp.linux-x86_64-3.7/f_src/spots.o build/temp.linux-x86_64-3.7/f_src/ellc.o build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7/ellc_f-f2pywrappers2.o -L/home/siegfried/anaconda3/envs/CARMENES/bin/../x86_64-conda_cos6-linux-gnu/sysroot/lib/../lib -L/home/siegfried/anaconda3/envs/CARMENES/bin/../x86_64-conda_cos6-linux-gnu/sysroot/lib/../lib -lgfortran -o build/lib.linux-x86_64-3.7/ellc/ellc_f.cpython-37m-x86_64-linux-gnu.so" failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for ellc
  Running setup.py clean for ellc
Failed to build ellc
Installing collected packages: ellc
    Running setup.py install for ellc ... error
    ERROR: Command errored out with exit status 1:
     command: /home/siegfried/anaconda3/envs/CARMENES/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_9uwjv6u/ellc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_9uwjv6u/ellc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-3sldqaxj/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-_9uwjv6u/ellc/
    Complete output (162 lines):
    running install
    running build
    running config_cc
    unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    running build_src
    build_src
    building extension "ellc.ellc_f" sources
    f2py options: []
      adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/fortranobject.c' to sources.
      adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7' to include_dirs.
      adding 'build/src.linux-x86_64-3.7/ellc_f-f2pywrappers2.f90' to sources.
    building data_files sources
    build_src: building npy-pkg config files
    running build_py
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/ellc
    copying ./__init__.py -> build/lib.linux-x86_64-3.7/ellc
    copying ./fluxes.py -> build/lib.linux-x86_64-3.7/ellc
    copying ./lc.py -> build/lib.linux-x86_64-3.7/ellc
    copying ./ldy.py -> build/lib.linux-x86_64-3.7/ellc
    copying ./rv.py -> build/lib.linux-x86_64-3.7/ellc
    copying ./version.py -> build/lib.linux-x86_64-3.7/ellc
    running build_ext
    customize UnixCCompiler
    C compiler: /home/siegfried/anaconda3/envs/CARMENES/bin/x86_64-conda_cos6-linux-gnu-cc -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -fPIC

    creating /tmp/tmp3li6raqz/tmp
    creating /tmp/tmp3li6raqz/tmp/tmp3li6raqz
    compile options: '-MMD -MF /tmp/tmp3li6raqz/file.c.d -c'
    x86_64-conda_cos6-linux-gnu-cc: /tmp/tmp3li6raqz/file.c
    customize UnixCCompiler using build_ext
    get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor']'
    customize Gnu95FCompiler
    Found executable /home/siegfried/anaconda3/envs/science/bin/x86_64-conda_cos6-linux-gnu-gfortran
    Found executable /home/siegfried/anaconda3/envs/CARMENES/bin/x86_64-conda_cos6-linux-gnu-gfortran
    Found executable /home/siegfried/anaconda3/envs/CARMENES/bin/x86_64-conda_cos6-linux-gnu-ld
    Found executable /home/siegfried/anaconda3/envs/CARMENES/bin/x86_64-conda_cos6-linux-gnu-ar
    Found executable /home/siegfried/anaconda3/envs/CARMENES/bin/x86_64-conda_cos6-linux-gnu-ranlib
    /home/siegfried/anaconda3/envs/CARMENES/lib/python3.7/site-packages/numpy/distutils/fcompiler/__init__.py:517: UserWarning: FFLAGS is used as is, not appended to flags already defined by numpy.distutils! Use NPY_DISTUTILS_APPEND_FLAGS=1 to obtain appending behavior instead (this behavior will become default in a future release).
      fflags = self.flag_vars.flags + dflags + oflags + aflags
    /home/siegfried/anaconda3/envs/CARMENES/lib/python3.7/site-packages/numpy/distutils/fcompiler/__init__.py:530: UserWarning: LDFLAGS is used as is, not appended to flags already defined by numpy.distutils! Use NPY_DISTUTILS_APPEND_FLAGS=1 to obtain appending behavior instead (this behavior will become default in a future release).
      linker_so_flags = self.flag_vars.linker_so
    /home/siegfried/anaconda3/envs/CARMENES/lib/python3.7/site-packages/numpy/distutils/fcompiler/__init__.py:540: UserWarning: LDFLAGS is used as is, not appended to flags already defined by numpy.distutils! Use NPY_DISTUTILS_APPEND_FLAGS=1 to obtain appending behavior instead (this behavior will become default in a future release).
      linker_exe_flags = self.flag_vars.linker_exe
    customize Gnu95FCompiler
    customize Gnu95FCompiler using build_ext
    building 'ellc.ellc_f' extension
    compiling C sources
    C compiler: /home/siegfried/anaconda3/envs/CARMENES/bin/x86_64-conda_cos6-linux-gnu-cc -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -fPIC

    creating build/temp.linux-x86_64-3.7/build
    creating build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7/build
    creating build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7
    compile options: '-Ibuild/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7 -I/home/siegfried/anaconda3/envs/CARMENES/lib/python3.7/site-packages/numpy/core/include -I/home/siegfried/anaconda3/envs/CARMENES/include/python3.7m -c'
    x86_64-conda_cos6-linux-gnu-cc: build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/fortranobject.c
    x86_64-conda_cos6-linux-gnu-cc: build/src.linux-x86_64-3.7/ellc_fmodule.c
    In file included from /home/siegfried/anaconda3/envs/CARMENES/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1830:0,
                     from /home/siegfried/anaconda3/envs/CARMENES/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                     from /home/siegfried/anaconda3/envs/CARMENES/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/fortranobject.h:13,
                     from build/src.linux-x86_64-3.7/ellc_fmodule.c:16:
    /home/siegfried/anaconda3/envs/CARMENES/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it with " \
      ^~~~~~~
    In file included from /home/siegfried/anaconda3/envs/CARMENES/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1830:0,
                     from /home/siegfried/anaconda3/envs/CARMENES/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                     from /home/siegfried/anaconda3/envs/CARMENES/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/fortranobject.h:13,
                     from build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/fortranobject.c:2:
    /home/siegfried/anaconda3/envs/CARMENES/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it with " \
      ^~~~~~~
    build/src.linux-x86_64-3.7/ellc_fmodule.c:109:12: warning: 'f2py_size' defined but not used [-Wunused-function]
     static int f2py_size(PyArrayObject* var, ...)
                ^~~~~~~~~
    compiling Fortran 90 module sources
    creating build/temp.linux-x86_64-3.7/ellc
    Fortran f77 compiler: /home/siegfried/anaconda3/envs/CARMENES/bin/x86_64-conda_cos6-linux-gnu-gfortran -Wall -g -ffixed-form -fno-second-underscore -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -O3 -funroll-loops
    Fortran f90 compiler: /home/siegfried/anaconda3/envs/science/bin/x86_64-conda_cos6-linux-gnu-gfortran -Wall -g -fno-second-underscore -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -O3 -funroll-loops
    Fortran fix compiler: /home/siegfried/anaconda3/envs/science/bin/x86_64-conda_cos6-linux-gnu-gfortran -Wall -g -ffixed-form -fno-second-underscore -Wall -g -fno-second-underscore -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -O3 -funroll-loops
    creating build/temp.linux-x86_64-3.7/f_src
    compile options: '-Ibuild/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7 -I/home/siegfried/anaconda3/envs/CARMENES/lib/python3.7/site-packages/numpy/core/include -I/home/siegfried/anaconda3/envs/CARMENES/include/python3.7m -c'
    extra options: '-Jbuild/temp.linux-x86_64-3.7/ellc -Ibuild/temp.linux-x86_64-3.7/ellc'
    x86_64-conda_cos6-linux-gnu-gfortran:f90: ./f_src/constants.f90
    x86_64-conda_cos6-linux-gnu-gfortran:f90: ./f_src/utils.f90
    ./f_src/utils.f90:1071:47:

     double precision function unitfunc(u,v,npar,par,verbose)
                                                   1
    Warning: Unused dummy argument 'par' at (1) [-Wunused-dummy-argument]
    ./f_src/utils.f90:1071:36:

     double precision function unitfunc(u,v,npar,par,verbose)
                                        1
    Warning: Unused dummy argument 'u' at (1) [-Wunused-dummy-argument]
    ./f_src/utils.f90:1071:38:

     double precision function unitfunc(u,v,npar,par,verbose)
                                          1
    Warning: Unused dummy argument 'v' at (1) [-Wunused-dummy-argument]
    ./f_src/utils.f90:1071:55:

     double precision function unitfunc(u,v,npar,par,verbose)
                                                           1
    Warning: Unused dummy argument 'verbose' at (1) [-Wunused-dummy-argument]
    x86_64-conda_cos6-linux-gnu-gfortran:f90: ./f_src/coords.f90
    x86_64-conda_cos6-linux-gnu-gfortran:f90: ./f_src/gauss_legendre.f90
    x86_64-conda_cos6-linux-gnu-gfortran:f90: ./f_src/solve_real_poly.f90
    x86_64-conda_cos6-linux-gnu-gfortran:f90: ./f_src/ellipse.f90
    x86_64-conda_cos6-linux-gnu-gfortran:f90: ./f_src/stellar.f90
    ./f_src/stellar.f90:189:0:

         if(d.eq.bad_dble) return

    Warning: 'd' may be used uninitialized in this function [-Wmaybe-uninitialized]
    ./f_src/stellar.f90:189:0: Warning: 'd' may be used uninitialized in this function [-Wmaybe-uninitialized]
    x86_64-conda_cos6-linux-gnu-gfortran:f90: ./f_src/spots.f90
    x86_64-conda_cos6-linux-gnu-gfortran:f90: ./f_src/ellc.f90
    ./f_src/ellc.f90:1815:0:

         flux_rv_flag(iobs,1) = (flux_1+flux_2+flux_3+refl_1+refl_2)/fnorm

    Warning: 'flux_3' may be used uninitialized in this function [-Wmaybe-uninitialized]
    ./f_src/ellc.f90:1558:0:

           ii = ii_2(iobs,i_spot)

    Warning: 'ii_2.dim[1].stride' may be used uninitialized in this function [-Wmaybe-uninitialized]
    ./f_src/ellc.f90:1558:0: Warning: 'ii_2.offset' may be used uninitialized in this function [-Wmaybe-uninitialized]
    ./f_src/ellc.f90:1371:0:

           ii = ii_1(iobs,i_spot)

    Warning: 'ii_1.dim[1].stride' may be used uninitialized in this function [-Wmaybe-uninitialized]
    ./f_src/ellc.f90:1371:0: Warning: 'ii_1.offset' may be used uninitialized in this function [-Wmaybe-uninitialized]
    ./f_src/ellc.f90:1559:0:

           df = df_2(iobs,i_spot)

    Warning: 'df_2.dim[1].stride' may be used uninitialized in this function [-Wmaybe-uninitialized]
    ./f_src/ellc.f90:1559:0: Warning: 'df_2.offset' may be used uninitialized in this function [-Wmaybe-uninitialized]
    ./f_src/ellc.f90:1372:0:

           df = df_1(iobs,i_spot)

    Warning: 'df_1.dim[1].stride' may be used uninitialized in this function [-Wmaybe-uninitialized]
    ./f_src/ellc.f90:1372:0: Warning: 'df_1.offset' may be used uninitialized in this function [-Wmaybe-uninitialized]
    compiling Fortran sources
    Fortran f77 compiler: /home/siegfried/anaconda3/envs/CARMENES/bin/x86_64-conda_cos6-linux-gnu-gfortran -Wall -g -ffixed-form -fno-second-underscore -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -O3 -funroll-loops
    Fortran f90 compiler: /home/siegfried/anaconda3/envs/science/bin/x86_64-conda_cos6-linux-gnu-gfortran -Wall -g -fno-second-underscore -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -O3 -funroll-loops
    Fortran fix compiler: /home/siegfried/anaconda3/envs/science/bin/x86_64-conda_cos6-linux-gnu-gfortran -Wall -g -ffixed-form -fno-second-underscore -Wall -g -fno-second-underscore -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -O3 -funroll-loops
    compile options: '-Ibuild/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7 -I/home/siegfried/anaconda3/envs/CARMENES/lib/python3.7/site-packages/numpy/core/include -I/home/siegfried/anaconda3/envs/CARMENES/include/python3.7m -c'
    extra options: '-Jbuild/temp.linux-x86_64-3.7/ellc -Ibuild/temp.linux-x86_64-3.7/ellc'
    x86_64-conda_cos6-linux-gnu-gfortran:f90: build/src.linux-x86_64-3.7/ellc_f-f2pywrappers2.f90
    /home/siegfried/anaconda3/envs/science/bin/x86_64-conda_cos6-linux-gnu-gfortran -Wall -g -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7/ellc_fmodule.o build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/fortranobject.o build/temp.linux-x86_64-3.7/f_src/constants.o build/temp.linux-x86_64-3.7/f_src/utils.o build/temp.linux-x86_64-3.7/f_src/coords.o build/temp.linux-x86_64-3.7/f_src/gauss_legendre.o build/temp.linux-x86_64-3.7/f_src/solve_real_poly.o build/temp.linux-x86_64-3.7/f_src/ellipse.o build/temp.linux-x86_64-3.7/f_src/stellar.o build/temp.linux-x86_64-3.7/f_src/spots.o build/temp.linux-x86_64-3.7/f_src/ellc.o build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7/ellc_f-f2pywrappers2.o -L/home/siegfried/anaconda3/envs/CARMENES/bin/../x86_64-conda_cos6-linux-gnu/sysroot/lib/../lib -L/home/siegfried/anaconda3/envs/CARMENES/bin/../x86_64-conda_cos6-linux-gnu/sysroot/lib/../lib -lgfortran -o build/lib.linux-x86_64-3.7/ellc/ellc_f.cpython-37m-x86_64-linux-gnu.so
    /home/siegfried/anaconda3/envs/science/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/siegfried/anaconda3/envs/science/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib/../lib/Scrt1.o: in function `_start':
    /home/rdonnelly/mc/conda-bld/compilers_linux-64_1534865402226/work/.build/src/glibc-2.12.2/csu/../sysdeps/x86_64/elf/start.S:99: undefined reference to `main'
    collect2: error: ld returned 1 exit status
    error: Command "/home/siegfried/anaconda3/envs/science/bin/x86_64-conda_cos6-linux-gnu-gfortran -Wall -g -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7/ellc_fmodule.o build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/fortranobject.o build/temp.linux-x86_64-3.7/f_src/constants.o build/temp.linux-x86_64-3.7/f_src/utils.o build/temp.linux-x86_64-3.7/f_src/coords.o build/temp.linux-x86_64-3.7/f_src/gauss_legendre.o build/temp.linux-x86_64-3.7/f_src/solve_real_poly.o build/temp.linux-x86_64-3.7/f_src/ellipse.o build/temp.linux-x86_64-3.7/f_src/stellar.o build/temp.linux-x86_64-3.7/f_src/spots.o build/temp.linux-x86_64-3.7/f_src/ellc.o build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7/ellc_f-f2pywrappers2.o -L/home/siegfried/anaconda3/envs/CARMENES/bin/../x86_64-conda_cos6-linux-gnu/sysroot/lib/../lib -L/home/siegfried/anaconda3/envs/CARMENES/bin/../x86_64-conda_cos6-linux-gnu/sysroot/lib/../lib -lgfortran -o build/lib.linux-x86_64-3.7/ellc/ellc_f.cpython-37m-x86_64-linux-gnu.so" failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/siegfried/anaconda3/envs/CARMENES/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_9uwjv6u/ellc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_9uwjv6u/ellc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-3sldqaxj/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
(CARMENES) siegfried@FD-Computers-PC:/mnt/d/WD/ellc-1.8.5/examples/KPD1946+4340$

**Comment by gulra001** [comment]
Did you find a solution to this issue yet? I am stuck at the same point.

**Comment by pmaxted** [comment]
User reports that this is not an ellc problem but an issue with f2py running in virtual environment. 

"I just switched to the base environment where the problem with f2py does not happen.  The problem is not related to the code, but the python wrapper.  It seems there is a compiler like -shared which solves this problem in all conda environments."

**Comment by pmaxted** [comment]
Dear Divya,
 See the update to this issue.
Regards,
 -Pierre

**Comment by gulra001** [comment]
Thank you so much for the update! 
Divya.
