### ISSUE TITLE
End ELLC - star 2 exceeds limiting radius

### ISSUE THREAD

**Issue by MilevaE** [pmaxted/ellc#6]
Hi, 

I want to explore a particular ultra-short period planets, and I notice that for such a configuration it seems to exist a limit in the radius of the planet (radius_2) of 6.9175500649212877E-003. 

Is there any physical reason why exist this limiting radius? if not, how can I modify this limit to allow my code run? 
This is an example of my configuration, and the message I get: 

```
P = 0.1 days, Rp = 1.5 earthRad
radius_1 = 0.16540150454142413
radius_2 = 0.015168173653443974
End ELLC - star 2 exceeds limiting radius
radius2 =    1.5168173653443974E-002
rlimit2 =    6.9175500649212877E-003
```

Thanks !

**Comment by pmaxted** [comment]
Yes - this physical reason is gravity 
[https://en.wikipedia.org/wiki/Roche_lobe](https://en.wikipedia.org/wiki/Roche_lobe)
