### ISSUE TITLE
Import fail fluxes (GCC v10)

### ISSUE THREAD

**Issue by mathtimm** [pmaxted/ellc#7]
Hello ! 
I get an error message when I try to import ellc_f : 

>>> from ellc import ellc_f
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/timmermans/miniconda3/lib/python3.7/site-packages/ellc/ellc_f.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _gfortran_os_error_at

From what I could find on the internet, the problem would come from the fact that I have the version 10 of GCC. Do you know if there is any way to resolve it without having to downgrade to an earlier version of GCC ? I'm afraid of damaging the rest of my system by doing that. 

Thanks a lot in advance for your help !

**Comment by pmaxted** [comment]
I have successfully installed and imported ellc-1.8.5 in a virtual environment using python 3.7.7 and gcc version 10.2.0 (MacPorts gcc10 10.2.0_4). Looks like your shell environment is not set up correctly. This is not an ellc issue so I am closing this issue.
